# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.0.3
group=dev.xylonity.nomendubium
java_version=17

# Common
minecraft_version=1.20.1
mod_name=Nomen Dubium
mod_author=Xylonity, crydigo
mod_id=nomendubium
license=GNU GPL v3.0
credits=
description=A mod that enhances the archaeology of the base game and adds new prehistorical content
minecraft_version_range=[1.20.1, 1.21)
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Fabric
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.16.9

# Forge
forge_version=47.4.0
forge_loader_version_range=[47,)

# Dependencies
knightlib_version=2.0.2

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
